### ISSUE TITLE
Add personal application status indicators

### ISSUE THREAD

**Issue by kxrt** [kxrt/sg-tech-internships#2]
As a user, I want to be able to keep track of my application progress without having to constantly switch back and forth this website and my personal list.

**Comment by kxrt** [comment]
Postponing this for a later month.

Firebase would probably be the easiest DB to set up for this, as a document based model is more conducive for user-specific configurations instead of indexing large SQL tables.

**Comment by ackselz** [comment]
Would love to contribute

**Comment by kxrt** [comment]
@ackselz Feel free to get in touch via email or LinkedIn and we can discuss how best to work this out!
